# Generated by Django 5.1.6 on 2026-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
